version: '2'
services:
  staticman:
    build: .
    env_file: .env
    ports:
      - '8080:3000'
    environment:
      NODE_ENV: production
      PORT: 3000
      GITHUB_TOKEN: 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
      RSA_PRIVATE_KEY: 

#        RSA private key to encrypt sensitive configuration parameters with.
#        the correct format starts with "-----BEGIN RSA PRIVATE KEY-----"
